---
- name: INSTALLING SAMBA
  hosts: all
  become: true

  tasks:
  
    - name: Installing packages
      package:
        name:
          - samba
          - samba-common
          - samba-client
        state: present
        
    - name: Create a directory if it does not exist
      file:
        path: /srv/tecmint/data
        state: directory
        mode: '0755'
        owner: nobody
        group: nobody
        
    - name: Allow SMB to modify files in /srv/tecmint/data
      sefcontext:
        target: '/srv/tecmint/data(/.*)?'
        setype: samba_share_t
        state: present
