---
- name: INSTALLING SAMBA
  hosts: all
  become: true

  tasks:
    - name: Installing packages
      ansible.builtin.package:
        name:
          - samba
          - samba-common
          - samba-client
        state: present
